//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.586
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Daiz.NES.Reuben.ProjectManagement {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Daiz.NES.Reuben.ProjectManagement.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;strings&gt;
        ///  &lt;set leveltype=&quot;0&quot;&gt;
        ///    &lt;block value=&quot;00&quot;&gt;Not Traversable&lt;/block&gt;
        ///    &lt;block value=&quot;01&quot;&gt;Not Traversable&lt;/block&gt;
        ///    &lt;block value=&quot;02&quot;&gt;Not Traversable&lt;/block&gt;
        ///    &lt;block value=&quot;03&quot;&gt;Not Traversable&lt;/block&gt;
        ///    &lt;block value=&quot;04&quot;&gt;Not Traversable&lt;/block&gt;
        ///    &lt;block value=&quot;05&quot;&gt;Not Traversable&lt;/block&gt;
        ///    &lt;block value=&quot;06&quot;&gt;Not Traversable&lt;/block&gt;
        ///    &lt;block value=&quot;07&quot;&gt;Not Traversable&lt;/block&gt;
        ///    &lt;block value=&quot;08&quot;&gt;Not Traversable&lt;/block&gt;
        ///    &lt;block val [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string blockstrings {
            get {
                return ResourceManager.GetString("blockstrings", resourceCulture);
            }
        }
        
        internal static byte[] default_graphics {
            get {
                object obj = ResourceManager.GetObject("default_graphics", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;graphicsinfo&gt;
        ///  &lt;graphics bank=&quot;0&quot; name=&quot;Raccoon Sprites #1&quot; /&gt;
        ///  &lt;graphics bank=&quot;1&quot; name=&quot;Raccoon Sprites #2&quot; /&gt;
        ///  &lt;graphics bank=&quot;2&quot; name=&quot;Raccoon Sprites #3&quot; /&gt;
        ///  &lt;graphics bank=&quot;3&quot; name=&quot;Raccoon Sprites #4&quot; /&gt;
        ///  &lt;graphics bank=&quot;4&quot; name=&quot;Global Level Sprites&quot; /&gt;
        ///  &lt;graphics bank=&quot;5&quot; name=&quot;Inventory Sprtes&quot; /&gt;
        ///  &lt;graphics bank=&quot;6&quot; name=&quot;Battle Mode Sprites #1&quot; /&gt;
        ///  &lt;graphics bank=&quot;7&quot; name=&quot;Battle Mode Sprites #2&quot; /&gt;
        ///  &lt;graphics bank=&quot;8&quot; name=&quot;Plains #1 A&quot;  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string default_graphics_names {
            get {
                return ResourceManager.GetString("default_graphics_names", resourceCulture);
            }
        }
        
        internal static byte[] default_palette {
            get {
                object obj = ResourceManager.GetObject("default_palette", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;sprites&gt;
        ///  &lt;spritedefinition id=&quot;01&quot; width=&quot;01&quot; height=&quot;01&quot; name=&quot;Unused&quot; group=&quot;1&quot; class=&quot;Error&quot;&gt;
        ///    &lt;sprite x=&quot;0&quot; y=&quot;0&quot; value=&quot;FC&quot; palette=&quot;2&quot; horizontalflip=&quot;false&quot; verticalflip=&quot;false&quot; table=&quot;FF&quot; /&gt;
        ///    &lt;sprite x=&quot;8&quot; y=&quot;0&quot; value=&quot;FE&quot; palette=&quot;2&quot; horizontalflip=&quot;false&quot; verticalflip=&quot;false&quot; table=&quot;FF&quot; /&gt;
        ///    &lt;sprite x=&quot;0&quot; y=&quot;0&quot; value=&quot;82&quot; palette=&quot;-3&quot; horizontalflip=&quot;false&quot; verticalflip=&quot;false&quot; table=&quot;-1&quot; /&gt;
        ///    &lt;sprite x=&quot;8&quot; y=&quot;0&quot; value=&quot;82&quot; palette=&quot;-3&quot; hor [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string default_sprites {
            get {
                return ResourceManager.GetString("default_sprites", resourceCulture);
            }
        }
        
        internal static byte[] default_tsa {
            get {
                object obj = ResourceManager.GetObject("default_tsa", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;music&gt;
        ///  &lt;track value=&quot;0&quot; name=&quot;None&quot; /&gt;
        ///  &lt;track value=&quot;1&quot; name=&quot;Grass Land&quot; /&gt;
        ///  &lt;track value=&quot;2&quot; name=&quot;Desert Land&quot; /&gt;
        ///  &lt;track value=&quot;3&quot; name=&quot;Water Land&quot; /&gt;
        ///  &lt;track value=&quot;4&quot; name=&quot;Giant land&quot; /&gt;
        ///  &lt;track value=&quot;5&quot; name=&quot;Sky Land&quot; /&gt;
        ///  &lt;track value=&quot;6&quot; name=&quot;Ice Land&quot; /&gt;
        ///  &lt;track value=&quot;7&quot; name=&quot;Pipe Land&quot; /&gt;
        ///  &lt;track value=&quot;8&quot; name=&quot;Dark Land&quot; /&gt;
        ///  &lt;track value=&quot;9&quot; name=&quot;Clouds&quot; /&gt;
        ///  &lt;track value=&quot;A&quot; name=&quot;Invinicible&quot; /&gt;
        ///  &lt;track value=&quot;B&quot; name=&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string music {
            get {
                return ResourceManager.GetString("music", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;specials&gt;
        ///  &lt;specialblocks leveltype=&quot;1&quot;&gt;
        ///    &lt;block appliesto=&quot;03&quot; upperleft=&quot;04&quot; upperright=&quot;05&quot; lowerleft=&quot;14&quot; lowerright=&quot;15&quot; palette=&quot;0&quot; /&gt;
        ///    &lt;block appliesto=&quot;05&quot; upperleft=&quot;08&quot; upperright=&quot;09&quot; lowerleft=&quot;18&quot; lowerright=&quot;19&quot; palette=&quot;1&quot; /&gt;
        ///    &lt;block appliesto=&quot;2F&quot; upperleft=&quot;00&quot; upperright=&quot;01&quot; lowerleft=&quot;10&quot; lowerright=&quot;11&quot; palette=&quot;0&quot; /&gt;
        ///    &lt;block appliesto=&quot;30&quot; upperleft=&quot;02&quot; upperright=&quot;03&quot; lowerleft=&quot;12&quot; lowerright=&quot;13&quot; palette=&quot;3&quot; /&gt;
        ///    &lt;block  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string special_definitions {
            get {
                return ResourceManager.GetString("special_definitions", resourceCulture);
            }
        }
        
        internal static byte[] special_graphics {
            get {
                object obj = ResourceManager.GetObject("special_graphics", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
